name: 'Create Branch'
description: 'Creates a branch'
author: 'anchan828 (anchan828@gmail.com)'
branding:
  icon: 'git-branch' 
  color: 'green'
inputs:
  branch:
    description: 'The branch to create'
    required: true
  from:
    description: 'The branch to use as base'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
